version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
        links:
            - app
    app:
        container_name: larvueadminda_app_1
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
            - cache
            - node
            - mailhog
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
        extra_hosts:
            - "larvueadmin.dda:172.19.0.1"
    node:
        container_name: larvueadminda_node_1
        image: node:8.12
        # build:
        #     context: ./
        #     dockerfile: deploy/node.docker
        volumes:
            - ./:/root/project
        tty: true
        environment:
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
        extra_hosts:
            - "larvueadmin.dda:172.19.0.1"
        working_dir: /root/project
    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=db"
        ports:
            - "33061:3306"
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"
    mailhog:
            build:
                context: ./
                dockerfile: deploy/mailhog.docker
            ports:
                - "8025:8025"
